### ISSUE TITLE
[CAD] - Add small hole to access camera lens fix screw

### ISSUE THREAD

**Issue by wilhelmzeuschner** [opulo-inc/lumenpnp#214]
The camera's lenses have small screws on the sides that allow to fix the lenses position. When tuning the focus it would be pretty bad if the lens could vibrate into another position over time. Currently this screw is not accessible.
In an optimal configuration this screw should be accessible when the camera is mounted, making adjustments easy.

Small holes should be added to:
FDM-0000-00_down-camera-mount_Body_001
FDM-0020-00_up-camera-mount_Body_001
Keep in mind that the lens assembly can only be mounted in two rotations (0° or 180°) in respect to the PCB.

Here are some pictures. I drilled a hole to be able to access the screw.
I added the hole to the opposite side, which is not ideal since it will be blocked when the camera is mounted. 
I did this because I already glued a connector onto the other side.
![image](https://user-images.githubusercontent.com/37621765/110376302-531d4480-8053-11eb-99be-fad3c9b53dd1.png)
![image](https://user-images.githubusercontent.com/37621765/110376317-56b0cb80-8053-11eb-9da3-1c2fa8f90230.png)
![image](https://user-images.githubusercontent.com/37621765/110376327-59abbc00-8053-11eb-93bf-44bcaa99fe17.png)

Optimal location:
![image](https://user-images.githubusercontent.com/37621765/110376998-274e8e80-8054-11eb-9909-0ab738e867fe.png)

**Comment by wilhelmzeuschner** [comment]
Here's what I changed for the up camera mount. No big changes but one mounting screw would get in the way. This one screw needs to be removed when you want to access the lenses' screw. Maybe not ideal, but still better than no access at all
I just edited the step file in Fusion since I'm not experienced in FreeCAD.
![image](https://user-images.githubusercontent.com/37621765/111072859-b9cfb180-84dc-11eb-8d52-86c2f0b22c8b.png)
![image](https://user-images.githubusercontent.com/37621765/111072864-be946580-84dc-11eb-87bf-6c78a52b117c.png)

**Comment by sphawes** [comment]
Sorry for dredging up an old thread, clearing out issues! This has been fixed as of v3, thank you for filing an issue @wilhelmzeuschner!

<img width="671" alt="Screenshot 2023-05-15 at 12 50 32 PM" src="https://github.com/opulo-inc/lumenpnp/assets/1865862/6cac0240-2329-4a30-b739-e395d1c4ee64">
<img width="597" alt="Screenshot 2023-05-15 at 12 50 47 PM" src="https://github.com/opulo-inc/lumenpnp/assets/1865862/e61afb3a-9b43-49ea-b637-c7d25b8ad427">
