### ISSUE TITLE
Anotate components with component specifications

### ISSUE THREAD

**Issue by G-Pereira** [opulo-inc/lumenpnp#315]
Add notes with voltage specifications for caps and etc on all PCB components.

**Comment by EdHayes3** [comment]
Is this for the silkscreen on the board?

**Comment by G-Pereira** [comment]
No, it's for KiCAD and the exports (BOM and só on)

**Comment by sphawes** [comment]
@G-Pereira is this still something you'd like to do?

**Comment by G-Pereira** [comment]
Maybe not for this rev but eventually yes to make it easier for us and others to quickly find alternatives when a part becomes EOL or not stocked.
