### ISSUE TITLE
[CAD] - 3d printer calibration for index prints

### ISSUE THREAD

**Issue by stuartpittaway** [opulo-inc/lumenpnp#320]
It would be useful for end users to be able to print a small shape containing the frequently used holes/parts of the Index machine to ensure their 3d printer is configured correctly before embarking on printing 48hours+ of real parts.

This way they can check M3/M5 tolerances and 20x20 extrusion holes

![image](https://user-images.githubusercontent.com/1201909/118960282-08754e00-b95b-11eb-8386-08601394aefc.png)

**Comment by sphawes** [comment]
@stuartpittaway I saw that you closed your PR around this change, @SyberxSpace can you upload a version of that killer calibration file you designed? would love to print it out and give it a whirl!

**Comment by lucian151** [comment]
Closed with the creation of the corndog model developed by @SyberxSpace a while ago.
