### ISSUE TITLE
[DOCS] Refactor links in Glossary

### ISSUE THREAD

**Issue by darigovresearch** [opulo-inc/lumenpnp#324]
As outlined in https://github.com/index-machines/index/pull/268#issuecomment-850848699 the current way of getting links to work in the glossary is by using headers however technically we should be using a definition list 

This is a good first issue and pull requests are welcome from the community to help refactor the glossary

**Comment by sphawes** [comment]
Closing this, we've changed how docs are structured. Thank you for the note @darigovresearch!
