### ISSUE TITLE
M3x10 bolt missing in the BOM (+ pulley spec)

### ISSUE THREAD

**Issue by noeldum** [opulo-inc/lumenpnp#414]
The BOM is missing the ISO7380 M3x10 bolt that mounts the nozzle stepper mount.

Just taking the opportunity to add another comment. The pulley spec should be more detailed in the BOM. Things like diameter, with or without teeth, number of teeth etc. I had to look at the amazon link to find out which one was to buy. On one part the part was out of stock and hard time finding out exactly the spec needed. Having that in the BOM well documented would have helped a lot.

**Comment by lucian151** [comment]
We'll be working on improving the BOM export process from FreeCAD. When we get to this, further information will be added about the exact specifications of pulleys! Thanks for submitting this issue.

**Comment by juantinazzo** [comment]
Hi! It would be great to add this kind of details to the HTML BOM in the releases. I checked the FreeCAD drawing to be sure of what exactly I needed to buy, just to be sure.

> Just taking the opportunity to add another comment. The pulley spec should be more detailed in the BOM. Things like diameter, with or without teeth, number of teeth etc. I had to look at the amazon link to find out which one was to buy. On one part the part was out of stock and hard time finding out exactly the spec needed. Having that in the BOM well documented would have helped a lot.
