### ISSUE TITLE
Text on FDM-0041-02 STL file is reversed

### ISSUE THREAD

**Issue by MakeItHackin** [opulo-inc/lumenpnp#444]
Downloaded new 3D prints from v2.0.0 - Milestone 2 Release.  The text on the STL file "FDM-0041-02" is reversed (mirrored)

**Comment by MakeItHackin** [comment]
it's possible the entire body is reversed.

**Comment by BrandonRemming** [comment]
> it's possible the entire body is reversed.

yup, a little cad error lol
![image](https://user-images.githubusercontent.com/69769058/153936547-a1d3de90-bdfc-4a84-9fbf-d5aa186358a1.png)

**Comment by stuartpittaway** [comment]
The body is a mirror, so it is correctly "reversed" - although the text would be better if it wasn't mirrored

**Comment by lucian151** [comment]
Closing as this is solved in v3
