### ISSUE TITLE
[FEATURE REQUEST] - Offer purchase for an "upgrade kit" for 2nd nozzle

### ISSUE THREAD

**Issue by MakeItHackin** [opulo-inc/lumenpnp#448]
I'm not sure about the terminology, but whatever would be needed to provide a 2nd nozzle/head for picking and placing two components simultaneously

**Comment by lucian151** [comment]
Closing as this is now complete! You can buy a 2nd toolhead upgrade kit from Opulo here - https://opulo.io/products/wired-toolhead-assembly
