### ISSUE TITLE
Part Number deboss missing on some parts large enough to have them

### ISSUE THREAD

**Issue by jonnerd154** [opulo-inc/lumenpnp#452]
Please fill out the following:
- **Build Number where this issue is present:** v2.0.0
- **Is this recording an active issue, or suggesting an improvement?:** suggesting an improvement
- **Are you just logging an issue, or do you have a solution in mind?:** solution in mind
- **Please describe the issue, including relevant part numbers and screenshots of the issue in CAD if possible:**
  Some parts are large enough to have PN's marked on them, but don't:
   - FDM-0017-02 (it's sister part FDM-0039 has one)
   - FDM-0055-00 (large enough, could be on the narrow edge)
   - #444
- **Please describe your suggestion solution, if you have something in mind:** Add PNs as above.

Thanks!

**Comment by lucian151** [comment]
Thanks for the issue report! We are moving away from engraved part number identifiers so this issue is going to be marked closed.
