### ISSUE TITLE
Ringlight - 74AHCT1G32 is footprint correct?

### ISSUE THREAD

**Issue by stuartpittaway** [opulo-inc/lumenpnp#454]
The file "ringLight_bom_jlc.csv" has an entry for:

```
"74AHCT1G32","U1","SOT-353_SC-70-5","C43450"
```

LCSC part C43450 is 
```
Manufacturer: Texas Instruments
Mfr. Part # SN74AHCT1G32DBVR
LCSC Part # C43450
Package SOT-23-5
```

**Notice the different footprint, SOT-23-5 vs SC_70-5**

Should the part be C350558 which is the SN74AHCT1G32DCKR - and that part uses the SC-70-5 foot print.

```
Manufacturer: Texas Instruments
Mfr. Part # SN74AHCT1G32DCKR
LCSC Part # C350558
Package SC-70-5
```

**Comment by casartar** [comment]
I have just tried to assemble the component. I can confirm that the LCSC number is not correct. Maybe I should read the issues before I order parts.
