### ISSUE TITLE
FDM-0021 Build Plate/Camera Foot

### ISSUE THREAD

**Issue by stuartpittaway** [opulo-inc/lumenpnp#476]
Please fill out the following:
- Build Number where this issue is present. (This is the same as the most recent tag number): 2.0.1
- Is this recording an active issue, or suggesting an improvement?: Active Issue
- Are you just logging an issue, or do you have a solution in mind?: Solution

- Please describe the issue, including relevant part numbers and screenshots of the issue in CAD if possible:

FDM-0021 is now considered optional, but is still shown on the Assembly and BOM

- Please describe your suggestion solution, if you have something in mind:

Rename FDM-0021 to a FDM-9XXX range and specify optional part in BOM

**Comment by lucian151** [comment]
fixed in v3
