### ISSUE TITLE
Improvement Locking PCB Through Holes

### ISSUE THREAD

**Issue by BenRinthLabs** [opulo-inc/lumenpnp#478]
This is more of a suggestion, but it'd be much easier to assemble and solder all the through hole components if you used locking through hole pads:

[https://www.sparkfun.com/tutorials/114](https://www.sparkfun.com/tutorials/114)

![mod1 005](https://user-images.githubusercontent.com/25337335/156484393-02bef364-3015-4fc0-bb5e-5ad688209136.jpg)

The holes are offset .005 inches in opposite directions allowing you to insert the part without it falling out when you flip the PCB over to solder the parts

Thanks!!!!

**Comment by stuartpittaway** [comment]
or perhaps change to use surface mounted connectors, so we could PNP it?

**Comment by CurlyTaleGames** [comment]
@stuartpittaway Through hole connectors/plugs are great for mechanical strength. You might be able to get away with surface mount for things that aren't plugged/unplugged often like the stepper drivers, but anything that is going to be under strain should really be through hole.

**Comment by G-Pereira** [comment]
I imagine the USBs are the only ones being frequently used so no issues there. Moving away from THT seems like a better option to me as well, but there is probably some connectors that will continue to be THT due to pricing and availability so I think this can be an interesting thing to discuss.
Just out of curiosity @CurlyTaleGames have you seen this in any off-the-shelf product?

**Comment by CurlyTaleGames** [comment]
@G-Pereira So I accidently did something similar on one of my PCB designs. 

I had a row of .1" header for two different parts all lined up, but the spacing between the two parts was off slightly. So when I put some header across both footprints it put some tension on the header pins holding it in place

![PXL_20220304_001144899](https://user-images.githubusercontent.com/25337335/156675207-bafbf140-a1e5-4519-baa8-4f015aa374ec.jpg)
![PXL_20220304_001214512](https://user-images.githubusercontent.com/25337335/156675230-0b633831-ce75-4baf-bd3f-a9052a77bcbb.jpg)

I thought that was a really nice way to hold a part in place so I did some Googling and found that Sparkfun article.

I haven't seen this offset locking footprint on other circuit boards before, but it's something I'm going to test out with my own PCBs next time I put in an order. I imagine it would work super well for holding parts in place and then just dip soldering the entire bottom of a PCB.

I still think THT components are a good solution for plugs/connectors. I know some people in Discord have had some issues with the surface mount vacuum sensor breaking off of the PCB. I'd be really careful about what you choose to be surface mount, a PCB with ripped off pads is a lot more time consuming to fix than hand soldering a through hole part.

**Comment by atanisoft** [comment]
> have you seen this in any off-the-shelf product?

I believe some of the AdaFruit and UnexpectedMaker products use the "locking" hole alignments. I'm also looking at integrating this into my projects as long as KiCad has a default footprint for it (likely they do).

**Comment by CurlyTaleGames** [comment]
@sphawes no problem!

**Comment by lucian151** [comment]
> This is a great idea! I agree that we should stick to THT so that we've got good strength on these connectors. I'll add this to the mobo rev04 project so it gets taken into consideration then. Thanks @CurlyTaleGames!

We ultimately wanted to do this but were unable to at this time, as this change would have broken REV04's compatibility with the REV03 pogo-pin QC Test Fixture. We'll likely update this QC fixture in the near future, so we'll revisit this suggestion then.

**Comment by CurlyTaleGames** [comment]
No worries! This feature is more of a quality of life thing for soldering through hole parts, you guys do what you gotta do :)

**Comment by sphawes** [comment]
Going to close this as we'll likely stick with inline with the mobo for now, but @CurlyTaleGames thank you for the idea! It actually got integrated into the feeder for the programming port so no connector is needed to flash new firmware to the feeder!
