### ISSUE TITLE
OpenPNP backlash compensation and calibration error

### ISSUE THREAD

**Issue by InfiniteNesLives** [opulo-inc/lumenpnp#495]
![image](https://user-images.githubusercontent.com/28371160/159174183-4db99573-0cd5-490d-9030-c28e94df8247.png)

Both myself and JelleWho are getting this error for both X&Y axis.  Looked around for the settings the error is complaining about but couldn't figure out what to do.  Anyone else figure out the solution for this error?

**Comment by jellewie** [comment]
Just to note, I have used the latest [machine.xml](https://github.com/index-machines/index/blob/01702144b94ddbe14eabd6cf24d7e3c43b42dba0/openpnp/machine.xml) from the repo (and all other setting). 

This exact issue doesn't ocured when I tried to set up my own profile. To me it seems to be something configured wrong in openPnP

**Comment by InfiniteNesLives** [comment]
I don't have time at the moment to drop all the details here, but JonMoyes sorted out a solution to this problem and we were both able to sucessfully complete the X & Y automatic backlash calibrations: https://discord.com/channels/688723670461448225/814870897722523699/969018146566570005

Still not sure what to recommend for speed and acceleration settings which are a big question to answer before really utilizing the backlash calibration from what I would guess..

**Comment by InfiniteNesLives** [comment]
After following Jon Moyes instructions I realized the suggested acceleration was quite slow.  My machine was painfully slow compared to beforehand.  Idk what acceleration settings are recommended, but I ended up picking 500/s^2 on Y, and 800/s^2 on X.

**Comment by G-Pereira** [comment]
Machine motion is getting significant changes. Please reopen if this is still an issue on 3.1.0+ release.
