### ISSUE TITLE
Adding mounting holes to nozzle stepper Z axis for pushpull feeder arm

### ISSUE THREAD

**Issue by InfiniteNesLives** [opulo-inc/lumenpnp#499]
This is a minor thing, and if isn't of interest to lumen devs I completely understand.  I just wanted to share the hack I made in case it is of interest.  I added some mounting holes to the Z axis / nozzle stepper mount which people usually print before they even receive their lumen kit.  Might be worth including the mounting holes in the official design that way users don't have to reprint if they want to test out pushpull feeders.

![image](https://user-images.githubusercontent.com/28371160/159854868-c3541ee9-4651-4bc8-b051-b0c78c891ea7.png)
![image](https://user-images.githubusercontent.com/28371160/159854945-3889da2b-8a66-4a25-a2e5-2bdffaa1a4d6.png)
stl files: [paul's pushpull feeder on lumen v1_0.zip](https://github.com/index-machines/index/files/8338933/paul.s.pushpull.feeder.on.lumen.v1_0.zip)

My freeCAD skills are nil, so I hacked it up with tinkercad if it's of any assistance for adding to the freecad model: https://www.tinkercad.com/things/8v5sV1uup20

discord discussion and other links:
https://discord.com/channels/688723670461448225/950431562443399178/953896256818790460

I fully understand this might be a conflict of interest, so feel free to simply close this issue if desired no harm no foul. :)  There are pushpull advancing arm designs that could mount to existing hardware on the Z axis, but my simple mounting holes open a number of options without conflicting with anything in the overall design.

**Comment by stuartpittaway** [comment]
Thanks for the info @InfiniteNesLives 

We would need the changes made in FreeCad to be kept consistent to the project.  I'm happy to make these changes if @sphawes  is okay to approve.
