### ISSUE TITLE
Corndog Not Modeled in FreeCAD

### ISSUE THREAD

**Issue by jazzychad** [opulo-inc/lumenpnp#515]
Please fill out the following:
- Build Number where this issue is present. (This is the same as the most recent tag number): 2.1.0
- Is this recording an active issue, or suggesting an improvement?: active
- Are you just logging an issue, or do you have a solution in mind?: solution
- Please describe the issue:

See page for reference: https://docs.opulo.io/tag/v2.1.0/docs/mechanical-assembly/printing-parts/

Instructions say only to download `3d-prints.zip` from the assets of latest tag (in this case, 2.1.0). The next step says to "Before printing the parts, print the calibration print. This is FDM-8000, ..."

This file is not included in the `3d-print.zip` archive, and it took me a while to realize it was actually a separate file in the assets list.

- Please describe your suggestion solution, if you have something in mind:

Either include this file in the `3d-prints.zip` archive, or deliberately specify in the documentation to download the `FDM-8000.stl` file separately, or both.

**Comment by atanisoft** [comment]
@jazzychad I agree it would be great to have this in the zip file rather than only on the release itself. It would require the FreeCAD file to be checked in and referenced as part of the actions.

**Comment by sphawes** [comment]
yup, this is really about getting the corndog modeled in FreeCAD. @SyberxSpace this would be a great foray into FreeCAD!

**Comment by lucian151** [comment]
@bricefekete is working on this! Reassigning to him.

**Comment by lucian151** [comment]
We will no longer be doing this as the LumenPnP comes pre-printed by Opulo.
