### ISSUE TITLE
Packing list for Lumen kit

### ISSUE THREAD

**Issue by InfiniteNesLives** [opulo-inc/lumenpnp#524]
Some users have been confused about whether items are missing from kits with extra holes in foam and such.

It would be helpful for a packing list to be either physically included with each lumen kit/shipment or including a digital packing list in opulo docs so items can be verified upon arrival.

**Comment by sphawes** [comment]
Thanks for the thought @InfiniteNesLives! We've added a short blurb to the website about what's included so folks know what to expect when opening the box.
