### ISSUE TITLE
Improperly defined Z axis in OpenPnP

### ISSUE THREAD

**Issue by qwertymodo** [opulo-inc/lumenpnp#539]
In OpenPnP, the Z axis is incorrectly defined, which causes some issues with several intended workflows, which according to the official documentation are supposed to operate on a coordinate system where Z=0 at the very top of the head travel, and use negative positions for everything.  On a dual-Z head like the Lumen, regardless of whether or not you're actually using both heads, the intention is that both heads should be mapped to Z-position 0 when the heads are even with each other, and then the values for each should go up or down from there.  Otherwise, when you map a Z position for something relative to one head, the position is completely different if you use the other head to try and reach the exact same position.  I believe I have figured out the proper way to set it up using the built-in [ReferenceMappedAxis](https://github.com/openpnp/openpnp/wiki/Transformed-Axes).  Note that I used 31 as my midpoint because that's what it is on my machine.  Substitute in your own measured midpoint (e.g. if your midpoint is 31.5, use 30.5/31.5/32.5 as your inputs, but still use 0/1 as the outputs)

1. Set up the physical Z axis as normal
2. Create two ReferenceMappedAxes: Z1 and Z2 (or ZL/ZR if you want to call them that)
- Z1: Input Axis: Z | Point A Input: 31 -> Output: 0 | Point B Input: 32 -> Output: 1
- Z2: Input Axis: Z | Point A Input: 31 -> Output: 0 | Point B Input: 30 -> Output: 1
3. Select Heads>H1>Nozzles>N1, click the drop-down menu under Z and select Z1
4. Repeat for Nozzle N2/Z2
5. Select Heads>Cameras>Top Camera, click the position tab, click the "Z" drop-down menu make sure **nothing** is selected

**Comment by sphawes** [comment]
Thank you for this @qwertymodo! I totally agree, and after hearing about how some folks have had an unfortunate nozzle collision with the camera, this makes a ton of sense.

I'll go through your notes and update the config file to have this implemented.
