### ISSUE TITLE
Mobo Cover

### ISSUE THREAD

**Issue by sphawes** [opulo-inc/lumenpnp#56]
The motherboard is fairly exposed when mounted to the bottom of the panel. A snap-on cover would be a great optional print for folks to have if they want to protect their motherboard.

**Comment by blucky10** [comment]
Is someone working on this, If not I would like to contribute.

**Comment by G-Pereira** [comment]
@blucky10  No one is working on it, feel free to start! Be sure you use FreeCAD being careful with topology references, watch [here](https://www.youtube.com/watch?v=e0pvw1weSuM)

**Comment by blucky10** [comment]
Can I get step file of Mother Board, with all the connectors to design the cut outs for them. As I have difficulty in obtaining the proper 3d files of the connectors.

![mobo1](https://user-images.githubusercontent.com/61348636/121398767-5508e380-c973-11eb-8625-f062a1d0a23e.png)
![mobo2](https://user-images.githubusercontent.com/61348636/121398775-563a1080-c973-11eb-9c9f-b0e2a149b04c.png)

**Comment by blucky10** [comment]
@G-Pereira , I'm ready with my initial design, thanks for the link, 
Just want to discuss some design consideration, will need a call I Guess. 

![image](https://user-images.githubusercontent.com/61348636/121813171-737b2180-cc88-11eb-9e9d-6b37a2ce50a6.png)

**Comment by G-Pereira** [comment]
Hello @blucky10 it looks nice but the new Mobo rev03 changed the board dimensions, now it's squared. The board isn't released yet but it is nearly ready.
Here it is the [step file](https://github.com/index-machines/index/blob/mobo-rev03/pnp/pcb/mobo/export/mobo-3D.step)

**Comment by G-Pereira** [comment]
@blucky10 are you on our Discord? We can have a call if you want!

**Comment by blucky10** [comment]
> @blucky10 are you on our Discord? We can have a call if you want!

Yes I'm on discord,  just messaged you please check

**Comment by Magpie-81** [comment]
I made a very simple protection cover for the Rev3 MOBO. It's available at Printables 
https://www.printables.com/model/242429-lumenpnp-mobo-protection-plate
