### ISSUE TITLE
Printing Parts

### ISSUE THREAD

**Issue by DavePaulsen** [opulo-inc/lumenpnp#577]
The calibration stl links are "404".

**Comment by atanisoft** [comment]
@DavePaulsen You can grab the calibration print from https://github.com/opulo-inc/lumenpnp-archive/releases/tag/v2.1.3 which is the last release prior to the repository move/rename.

**Comment by DavePaulsen** [comment]
Thanks.

**Comment by kaklik** [comment]
The same issue in docs gets me there too.   The correct solution should be a repair [the link](https://github.com/index-machines/index/releases/latest/download/FDM-8000_corndog.stl) in [the docs page](https://docs.opulo.io/docs/mechanical-assembly/printing-parts/#calibration-print).

**Comment by theacodes** [comment]
Fixed via https://github.com/opulo-inc/docs/commit/c97187323566b5943916951c22d114c39255706b
