### ISSUE TITLE
Generate OpenPnP Machine config file with relaeses 

### ISSUE THREAD

**Issue by gabeseltzer** [opulo-inc/lumenpnp#579]
Per discussion on [Google Drive](https://docs.google.com/document/d/1EmLirJEJiujUfkhmwnZN0K0BsEuByz94-yeLfNy0x7c/edit?disco=AAAAa0uvA4Q), @sphawes liked my idea of splitting out the OpenPnP machine config into the releases artifacts so that people can get that easily when they need it.

**Comment by sphawes** [comment]
Fixed in [this commit](https://github.com/opulo-inc/lumenpnp/commit/0309d77746c9cb07c935c6cf47d26ab56a9b7cee)! Closing.
