### ISSUE TITLE
Rear Legs have structural weakness at lower 2020 extrusion socket.

### ISSUE THREAD

**Issue by atanisoft** [opulo-inc/lumenpnp#581]
Please fill out the following:
- Build Number where this issue is present. (This is the same as the most recent tag number): 2.x (all versions)
- Is this recording an active issue, or suggesting an improvement?: Active with suggestion to improve
- Are you just logging an issue, or do you have a solution in mind?: Solution in mind
- Please describe the issue, including relevant part numbers and screenshots of the issue in CAD if possible:
The positioning of the lower 2020 extrusion socket results in a weak spot when printed which can result in leg failure. Picture below is from my original build which I've now rebuilt using the "wide body" modification.
- Please describe your suggestion solution, if you have something in mind:
Extend the return of the rocker foot to be in the middle (or above) the 2020 extrusion socket. Adding a 0.25mm tolerance to all sides of the 2020 socket will help account for printer differences as well as a 45deg chamfer on the entry face (if not already there).

![PXL_20220620_164101445](https://user-images.githubusercontent.com/6457044/174647886-db23caca-7bd2-4d60-a2dd-fb74f1af78b3.jpg)

**Comment by qwertymodo** [comment]
Might as well tack on here that the square holes have 0 tolerance built in, so that really needs to be fixed. Lots of people cracking legs trying to insert the V-slot extrusion, and it isn't even necessary for it to be *that* snug, because all of those holes also have M5 T-nut mounts.
