### ISSUE TITLE
Small swing on vacuum sensor readings

### ISSUE THREAD

**Issue by Memnarch1113** [opulo-inc/lumenpnp#585]
Some users are noticing a swing in the readings from the vacuum sensor on the motherboard. The swings are large enough to make it impossible to tell if the LumenPnP has actually picked up a component because the readings are too inconsistent. 

We're working on a fix that involves removing the vacuum sensor, adding in a hotfix PCB, and then reinstalling the vacuum sensor.

Internal tracking of folks who are interested in the hotfix PCB [here](https://www.notion.so/opulo/Small-swing-on-vacuum-sensor-readings-baeeae3a2dd14f9bbe6994489c6f4007).

**Comment by lucian151** [comment]
Fixes with Interposer PCB addition to LumenPnP Motherboard
