### ISSUE TITLE
FDM-0044-01 (x-gantry-roller-carriage) and x-gantry-front: Roller axle distances do not match

### ISSUE THREAD

**Issue by Magpie-81** [opulo-inc/lumenpnp#586]
The distance between the axle holes on the x-gantry-roller-carriage measures 62.5mm, the distance of the axle slots in the x-gantry-front measures 62.0mm.

The entire CAD model around the x-gantry in the assembly seems very misaligned. The rollers on top of the extrusion don't line up with the bottom rollers, and there is visible interference between the different parts.
I was looking at the latest assembly.FCStd file commited on Jul 13, 2022 in the v2.2.0 main.

**Comment by G-Pereira** [comment]
Rollers will be removed in next version
