### ISSUE TITLE
x-gantry-back and x-gantry-front M5 holes do not match

### ISSUE THREAD

**Issue by theacodes** [opulo-inc/lumenpnp#603]
As of 64cf8ded, the V3 x-gantry-front and x-gantry-back have mismatched M5 bolt holes. See the images below, the blue dimensions (added by me) show that the distance between the top M5 holes and bottom M5 slots are different by 1mm.

<img width="981" alt="Screen Shot 2022-09-11 at 11 25 14 AM" src="https://user-images.githubusercontent.com/250995/189536052-eeb7d035-6426-41b0-a0b3-8abdb75a82ca.png">
<img width="982" alt="Screen Shot 2022-09-11 at 11 23 51 AM" src="https://user-images.githubusercontent.com/250995/189536053-096460a8-453a-4bd1-b215-5d68046433c8.png">

This issue was noticed by Discord user mylast. Possibly related to #586.

**Comment by G-Pereira** [comment]
This has been removed in favor of a linear rail in the upcoming version
