### ISSUE TITLE
Readme broken link to feeder.png

### ISSUE THREAD

**Issue by spuder** [opulo-inc/lumenpnp#623]
[feeder/README.md](https://github.com/opulo-inc/lumenpnp/blob/main/feeder/README.md
) has a broken link that references `feeder.png`, however there is no feeder.png anywhere. 

I tried to fix the link, but I was unable to find the image 

https://github.com/opulo-inc/lumenpnp/blob/main/feeder/README.md

https://github.com/opulo-inc/lumenpnp/blob/main/img/feeder.png

**Comment by sphawes** [comment]
thanks for the note @spuder! we've moved the feeder source to a new repo with proper image linking: https://github.com/opulo-inc/feeder
