### ISSUE TITLE
v3 Kit Assembly documentation missing from site

### ISSUE THREAD

**Issue by BenRinthLabs** [opulo-inc/lumenpnp#625]
The docs site [https://docs.opulo.io/](https://docs.opulo.io/) is missing documentation for the assembly of the v3 version of the kit. I've taken my lumen apart a few times now, so I feel confident I can figure out how to assemble v3 but others who are new might not.

**Comment by lucian151** [comment]
This feedback has been addressed with the launch of [ohai.opulo.io](https://ohai.opulo.io/)!
