### ISSUE TITLE
Add clearance for access to bolt heads on Y gantries

### ISSUE THREAD

**Issue by BenRinthLabs** [opulo-inc/lumenpnp#627]
This is more of an improvement than an issue, but it'd be nice to be able to access these screw heads on the Y gantries, should be a pretty simple cad change.

![PXL_20221107_1911525262](https://user-images.githubusercontent.com/25337335/200395306-1faa5ef9-5bfd-4236-b651-92f83e805e47.jpg)

**Comment by lucian151** [comment]
Hey @CurlyTaleGames this is already fixed in the V3.0.1 file set and onwards -are you seeing this issue with the most recent design release?

**Comment by CurlyTaleGames** [comment]
@lucian151 weird, I downloaded V3.0.1 from the releases and printed everything:
![image](https://user-images.githubusercontent.com/25337335/201788472-0709b973-6725-4345-a3de-d290a1c80add.png)

I just checked out y-gantry-x2.stl and it matches the file I printed:
![image](https://user-images.githubusercontent.com/25337335/201788648-e80c54c9-82a4-4d24-8603-ccfcc0a3767c.png)

Here is are screenshots of the x-idler-mount.stl:
![image](https://user-images.githubusercontent.com/25337335/201788861-dc29fc03-fc3a-4868-a2aa-1e08c5abb64f.png)

And the x-motor-mount.stl:
![image](https://user-images.githubusercontent.com/25337335/201788963-6fb6898c-3989-4d83-9f4b-81e6328d8b9f.png)

I just downloaded V3.0.2 from releases and those parts match the parts I have in V3.0.1

If those cad changes have been made it doesn't look like they are in the STL files in the releases

**Comment by CurlyTaleGames** [comment]
For fun I downloaded the Freecad x-idler-mount and exported it out as a stl 
![image](https://user-images.githubusercontent.com/25337335/202879958-31590526-7ce6-4a68-b320-1a27dea41f3c.png)

Then added that stl as well as the stl from the 3.0.2 release into prusa slicer and matched them up, and can confirm they are the same:
![image](https://user-images.githubusercontent.com/25337335/202879942-17c977e7-8f1e-4701-b01a-afd7633a794c.png)

Is there a CAD branch that has this change that needs to get merged in?

**Comment by lucian151** [comment]
@CurlyTaleGames Ah I see now, I'm sorry for misunderstanding your suggestion. I had updated these pieces in 3.0.1 to fix bolt heads that were sticking out far enough to interfere with the removable x-gantry assembly. What you'r suggesting is entirely different than my earlier change, and I'm not sure how I didn't realize that earlier.

This isn't a bad idea - I'll take it into consideration the next time I have to touch these two models. If you're interested in taking a stab at it before I get to it, I'd be happy to review a PR!
