### ISSUE TITLE
Feeder Floor PCB insufficient vias on ground

### ISSUE THREAD

**Issue by solarmax1** [opulo-inc/lumenpnp#639]
I was looking at the PCB design for the feeder floor and noticed that all of the ground current from the feeder to the feeder floor passes through 1 ground via.   I don't know what the current is,  but 1 via is not enough.  I would add a bunch of vias in that area.  There is enough room, and it adds zero cost.

![Untitled](https://user-images.githubusercontent.com/7441359/209873911-3185eace-2879-46dc-9806-37c9a8ee5419.jpg)

**Comment by sphawes** [comment]
this is referencing an old version of the source that was erroneously kept in the repo. the full source for the feeder (which has much better grounding on the slot) can be found here: https://github.com/opulo-inc/feeder
