### ISSUE TITLE
MOBO Bom Questions

### ISSUE THREAD

**Issue by beamsjr** [opulo-inc/lumenpnp#646]
This issue is related to the release version [v3.0.0](https://github.com/opulo-inc/lumenpnp/releases/tag/v3.0.0) 

File in question: mobo-bom.csv

Line 9 states that it is a 22uf 0805 capacitor,  there are 2 linked LCSC part numbers: C5674 and C17024.  The first is a 6.3V 22uF, and the other is 10V 10uF. 

Line 29 states 120R resistor, and has 2 parts: C139879 which is a 36kΩ resistor, and C131390 which is a 120Ω resistor. 

Line 34 same thing, says 10k, has C115295 C139879 listed, C115295 being 10k, and C139879 being 36k.

Could you please clarify why there are 2 different parts in these this columns?

**Comment by stuartpittaway** [comment]
Hi, the BOM is automatically generated (by kibot) but looks like it's not doing a very good job!

I suggest downloading and using Kicad to examine the schematic, kicad 5 (the older version)
