### ISSUE TITLE
Need strain relief on Z-gantry...

### ISSUE THREAD

**Issue by nweaver** [opulo-inc/lumenpnp#659]
The connecting wires between the Z-gantry and the head itself are under a fair deal of stress:
In particular, if the connection breaks (yellow wire in my case) the tool head itself gets very hot and deforms the z-gantry.

**Comment by lucian151** [comment]
Hi @nweaver, thank you for reporting this, we're taking a serious look at how to incorporate your feedback into machines moving forward. Thinking this will take the form of zip-tie mounting features on z-gantry print.

**Comment by RRudi92** [comment]
![20230724_152030](https://github.com/opulo-inc/lumenpnp/assets/64029642/771c9b85-a786-4a94-9f47-b6c9e855d6d9)
Happened to me too. Tried to fix it and strengthen it with Hotmelt, but it broke again. I had to Disable N2.

**Comment by RRudi92** [comment]
Suggestion: 
Does the Z-Axis NEED over 30mm of travel (Overall travel 60mm)? Most Parts that will be P'n'P'd with such a mashine will be rather flat. Maybe TO Mosfet or the like.
Mounting the Heads lower (e.g. 15mm over PCB-Hight) will reduce travel distance and strain on the cabling.
