### ISSUE TITLE
Feeder folder should be removed from this repo

### ISSUE THREAD

**Issue by Jnesselr** [opulo-inc/lumenpnp#663]
Opulo has a distinct feeder folder in here but also a feeder repo with more up to date files. The feeder folder here should be deleted.

Also, I noticed all the issue templates still say "index" when filling this out.

**Comment by sphawes** [comment]
Thank you @Jnesselr! Fixed in [e85a91a](https://github.com/opulo-inc/lumenpnp/commit/e85a91ac5de64a7db6f5a585e97629f70c0349f3).
