### ISSUE TITLE
Toolhead idler pulley rubs against screw and 3D printed part

### ISSUE THREAD

**Issue by juantinazzo** [opulo-inc/lumenpnp#667]
# Version Number
3.0.5

# Bugfix or Enhancement
Issue

# Description
The toolhead GT2 idler pulley may rub against screw and x-gantry-front.  Depending on the exact model of the pulley, the bearing surface rubs against the screw, and also with the 3D printed part, causing friction. I can confirm this is an issue with my build. My 3D printer is correctly calibrated and the screw is the same one as the one stated in the BOM. 

![image](https://github.com/opulo-inc/lumenpnp/assets/28155846/5f314383-6275-4d36-90c1-3b0aea6da521)

# Suggested Solution
Make 3D printed contact surface a tiny bit smaller in diameter at the tip, and add an optional washer (it may be 3D printable) to the side of the screw head. The washer has to be small enough to not cause the same problem it's trying to fix.

**Comment by lucian151** [comment]
I know it seems like there's a collision when you reference CAD, but with the pulleys we use on the production line alongside our [assembly processes for the toolhead](https://ohai.opulo.io/lumen/x-gantry/#x-gantry-toolhead-assembly) this issue doesn't occur on LumenPnP machines built by Opulo as far as I've seen. 

The step quoted below from the linked OHAI assembly SOP is also really critical in avoiding this issue. @juantinazzo can you try this and report if it fix the issue for you?

- Attach z-gantry-left and z-gantry-right onto each respective linear rail carriages + z-gantry-backplate with 4x M3x8 bolts per side
   - Align each z-gantry to be parallel with the linear-rail by lightly pressing it outward with your hand, away from the mid-plane of the x-gantry-subassembly
   - As these bolts are tightened ensure that the z-gantry doesn’t collide with the z-idler’s bolt head
   - Tighten bolts to 0.3 N/M, moving in a star pattern

    ![image](https://github.com/opulo-inc/lumenpnp/assets/33263520/25e2a62a-061d-4758-8496-89772fc8ed77)
