### ISSUE TITLE
Motors are disabled after a way too short time

### ISSUE THREAD

**Issue by RRudi92** [opulo-inc/lumenpnp#670]
# Version Number
Marlin bugfix-2.1.x (May 19 2023)
2023-04-05_08-24-36.0aa4ae8

# Bugfix or Enhancement
Bugfix / Enhancement

# Description
The Motors are disabled after a few Minutes. A Position loose is possible.

# Suggested Solution
The Motors should NEVER be disabled, as long as the machine is active. Sometimes you have to do a short break while P'n'Ping, and suddenly you have lost a step or to (without recognizing)

**Comment by wolfstrassen** [comment]
I second this. Loosing a step could be critical when doing micro bga ICs

**Comment by wolfstrassen** [comment]
Did you try setting up the time with M18/M84?

**Comment by RRudi92** [comment]
Yes, M84 S5000 did the trick. It seems to be persistent saved on the machine.

**Comment by sphawes** [comment]
this has been fixed in the v3.2 release!
