### ISSUE TITLE
Updating Firmware documentation is under Kit assembly (v2)

### ISSUE THREAD

**Issue by wolfstrassen** [opulo-inc/lumenpnp#671]
# Version Number 
3.0.5

# Enhancement

# Description
Currently the documentation to upgrade the firmware is under the Kit assembly (v2) menu on docs.opulo.io, as a v3 user I tought for a while there was no firmware update documentation because I would not look under a version lower than mine.

# Suggested Solution
Change the Updating firmware  section to another section (probably misc)

**Comment by sphawes** [comment]
thanks for the note! this now lives in the new "Guides" section: https://docs.opulo.io/guides/update-firmware/
