### ISSUE TITLE
Linear Rail Bolts Marginally Interfere with X Gantry Back

### ISSUE THREAD

**Issue by lucy-chapar** [opulo-inc/lumenpnp#676]
# Version Number
V3.1.0

# Bugfix or Enhancement
Bug

# Description
The linear rail mounting bolts intersect x-gantry-back by 0.15mm 
![Screenshot 2023-08-30 at 4 15 46 PM](https://github.com/opulo-inc/lumenpnp/assets/33263520/c1e9c1b8-73f3-4d6d-ab08-5932b3ed5a58)

# Suggested Solution
Lower the affected face on x-gantry-back by 2mm

**Comment by lucian151** [comment]
In reality this probably isn't a real problem after you consider tolerance stack up making all the involved parts something other than nominal. A printed x-gantry-front is likely to be a little taller than nominal. A bolt is likely to be a little shorter than nominal.

**Comment by lucian151** [comment]
I will add 2 circular cutouts here to address the possible interference: ![Screenshot 2023-08-30 at 7 04 02 PM](https://github.com/opulo-inc/lumenpnp/assets/33263520/b90ece6f-b6f8-43d6-84a4-bdd40da6b96f)
