### ISSUE TITLE
Hello, every time you reopen Openpnp Feida's slot address: None, you need to click Find to display the slot address

### ISSUE THREAD

**Issue by 84864797** [opulo-inc/lumenpnp#683]
Hello, every time you reopen Openpnp Feida's slot address: None, you need to click Find to display the slot address

May I ask how to solve it?

**Comment by sphawes** [comment]
It's much easier to just scan every address! Check out the docs page here showing you how to scan every address: https://docs.opulo.io/feeders/5-openpnp-setup/feeder-openpnp-setup/#finding-feeders
