### ISSUE TITLE
Rev 4 Mobo has a schematic labeling error for X, Y limits

### ISSUE THREAD

**Issue by troth530** [opulo-inc/lumenpnp#684]
# Version Number
Rev 4 Mobo

# Bugfix or Enhancement
Bug in schematic label

# Description
This implies diag pins for X and Y are not connected, but they are.  
![image](https://github.com/opulo-inc/lumenpnp/assets/60661971/739c7aff-7cdf-4f77-802a-3b3075f2e5d8)

# Suggested Solution
Label fix. I'm not familiar with Kicad, but seems like a label issue because usually routing to diff nets is not possible

**Comment by G-Pereira** [comment]
This has been redesigned in upcoming motherboard revision. Thank you!
