### ISSUE TITLE
Proper Motherboard Enclosure

### ISSUE THREAD

**Issue by sphawes** [opulo-inc/lumenpnp#699]
# Version Number
REV04 mobo (v3.1.2 of the Lumen) 

# Bugfix or Enhancement
Enhancement

# Description
The current method of physically protecting the motherboard from damage or ESD is a bottom cover to prevent parts from falling onto it, and a top cover to prevent mechanical damage. This should be improved for better ESD and mechanical protection.

# Suggested Solution
The motherboard and pneumatic components should be fully enclosed in a printed case. This includes moving the motherboard and pneumatics to the left side of the machine, mounted to the bottom rail of the Left Y Gantry, clearing space on the staging plate for an easier time mounting strip feeders and board mounting hardware.

This extra layer of protection should help greatly with ESD concerns. I doubt PLA is the most ideal choice, but it is accessible to builders. This is a strategy that the Prusa Mini uses for its controller enclosure. Any thoughts on the efficacy of PLA in this role is greatly appreciated!

Here's a rough mockup of the idea:

![Screenshot 2024-01-04 at 12 42 16 PM](https://github.com/opulo-inc/lumenpnp/assets/1865862/eb7ce4f4-13dd-4fb3-9dbb-b249b81bc3cf)

**Comment by lucian151** [comment]
![Image](https://github.com/opulo-inc/lumenpnp/assets/33263520/90fec679-0651-431e-9962-f12ff1260acb)

**Comment by lucian151** [comment]
![Image](https://github.com/opulo-inc/lumenpnp/assets/33263520/29239d50-c777-4c45-9aa6-90364223ad81)

**Comment by G-Pereira** [comment]
Addressed on v4
