### ISSUE TITLE
Missing GPIO Header

### ISSUE THREAD

**Issue by sphawes** [opulo-inc/lumenpnp#700]
# Version Number
REV05b0

# Bugfix or Enhancement
Enhancement

# Description
The REV05b0 board does not have a GPIO header for hacking the Lumen to control arbitrary peripherals.

# Suggested Solution
A DNP footprint on the board that folks can solder a header into that provides a couple GPIO, I2C, and 3v3/GND.

**Comment by G-Pereira** [comment]
Added!
