### ISSUE TITLE
Where is 3d assembly design files ? 

### ISSUE THREAD

**Issue by hemangjoshi37a** [opulo-inc/lumenpnp#709]
Where is 3d assembly design files ? 
I cant fine one . please  provide if anyone has . thanks

**Comment by hemangjoshi37a** [comment]
@stuartpittaway thank you so much for helping out. 👍👍

**Comment by hemangjoshi37a** [comment]
@stuartpittaway  is there a build guide available for like step by step process or something like this ?

**Comment by stuartpittaway** [comment]
You've got the documentation over at https://docs.opulo.io/
