### ISSUE TITLE
Is proteus vsm based pcb supported in lumenpnp?

### ISSUE THREAD

**Issue by hemangjoshi37a** [opulo-inc/lumenpnp#710]
Is proteus vsm based pcb supported in lumenpnp?

**Comment by sphawes** [comment]
OpenPnP is the software that would determine support for this filetype. Check out their wiki here: https://github.com/openpnp/openpnp/wiki/Importing-Centroid-Data

**Comment by hemangjoshi37a** [comment]
@sphawes thank you for resolving this
