### ISSUE TITLE
Starting BYOP build, which release should I print?

### ISSUE THREAD

**Issue by rxs621** [opulo-inc/lumenpnp#717]
Hello,

I'm starting a build of the Lumen PnP and was wondering for the instructions available online for the BYOP, does that correspond with v2.2 or v3.2 parts?

Thanks

**Comment by sphawes** [comment]
All the BYOP instructions are relevant for any v2 designs! But i highly recommend building the most recent version (v3.2 as of this writing) and just use ohai.opulo.io to help with assembly. also see this section of the FAQ: https://docs.opulo.io/faq/#how-do-i-build-one
