### ISSUE TITLE
Error while reading machine.xml in new configuration v3.2-01

### ISSUE THREAD

**Issue by kheygetyan** [opulo-inc/lumenpnp#718]
Uploaded [LumenPnP-Config-v3.2-01.zip](https://github.com/opulo-inc/lumenpnp/releases/download/v3.2.0/LumenPnP-Config-v3.2-01.zip) to a clean folder (.openpnp2)
And the OpenPnp gives an error when launched
![2002202401](https://github.com/opulo-inc/lumenpnp/assets/121425310/665904d2-a6c9-490e-9ca2-e92973d34662)

**Comment by sphawes** [comment]
There's a new version of the config in the V3.2 release now! Does that fix the issue?

**Comment by atanisoft** [comment]
This is likely an issue due to difference in version of OpenPnP. Which version are you using and which is @sphawes using for the release config?

**Comment by kheygetyan** [comment]
> This is likely an issue due to difference in version of OpenPnP. Which version are you using and which is @sphawes using for the release config?

I'm using OpenPnP 2.0

**Comment by atanisoft** [comment]
Can you cross check the version in the about box? I'd expect a date / time stamp on it and not just 2.0 (which is unfortunately what they almost all are labeled)

**Comment by kheygetyan** [comment]
> Can you cross check the version in the about box? I'd expect a date / time stamp on it and not just 2.0 (which is unfortunately what they almost all are labeled)

OpenPnP Version: 2023-03-15_00-30-21.460d8aa

**Comment by atanisoft** [comment]
@kheygetyan Please upgrade your OpenPnP build to the 2023-04-05 release as linked from https://docs.opulo.io/openpnp/install/.

**Comment by kheygetyan** [comment]
> @kheygetyan Please upgrade your OpenPnP build to the 2023-04-05 release as linked from https://docs.opulo.io/openpnp/install/.

Thank you!
With the Test version of the OpenPnp now starts without errors
