### ISSUE TITLE
Please send be DIY build guide doc link if possible.

### ISSUE THREAD

**Issue by hemangjoshi37a** [opulo-inc/lumenpnp#726]
Please send be DIY build guide doc link if possible.

**Comment by atanisoft** [comment]
https://docs.opulo.io/byop/ should cover the assembly, for the PCBs you are going to need to follow the PCB BOMs for assembly of components.

**Comment by lucian151** [comment]
@hemangjoshi37a an additional source of info is https://ohai.opulo.io/lumen/, which is Opulo's in-house assembly instructions for building the LumenPnP

**Comment by hemangjoshi37a** [comment]
@atanisoft @lucian151  thank you so much 👍
