### ISSUE TITLE
i want to modify the head of the lumen pnp 3.1/3.2 so i can glue and some other things. now i want to modify the head but i cant draw in freecad but i can in solidworks. is there anyone who can provide me with the drawings of this machine and in particular the drawing of the head where the camera and arms etc are attached?

### ISSUE THREAD

**Issue by panaken** [opulo-inc/lumenpnp#732]
# Version Number
What is the latest known version number where this issue is present?

# Bugfix or Enhancement
Is this issue a bug with the configs, or a potential enhancement?

# Description
Please describe the issue. Be sure to include relevant parts and photos/video if possible.

# Suggested Solution
Please describe a suggested solution, if you have one in mind.

**Comment by lucian151** [comment]
Hi @panaken you can contact us via support@opulo.io for help on this!
